### ISSUE TITLE
Demo Deployment Checklist

### ISSUE THREAD

**Issue by Tarunshrma** [Into-the-Fathom/fathom-stablecoin-smart-contracts#96]
- [ ] Deploy Smart Contracts
- [ ] Deploy StableCoin subgraph
- [ ] Deploy DAO Subgraph
- [ ] Deploy Liquidation Bot
- [ ] Deploy Frontend

**Comment by Majorplaydev** [comment]
Are there any good first issues I can work on?
